name: Deploy From Main

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Get Latest Code
        uses: actions/checkout@v2

      - name: use NodeJS ${{matrix.node-version}}
        uses: actions/setup-node@main
        with:
          node-version: ${{matrix.node-version}}

      - name: Copy Dist ENV to ENV 
        run: cp .env.dist .env
        run: find / -print

      - name: Build Project
        run: |
          npm install yarn -g
          npm cache clean --force
          yarn install
          yarn run prodBuild
        
      - name: List Output Files
        run: find build/ -print

      - name: Sync Files to Server
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
           server: ${{ secrets.SERVER }}
           username: ${{ secrets.FTP_USERNAME }}
           password: ${{ secrets.FTP_PASSWORD }}
           local-dir: build/
